[project]
name = "test-project"
version = "0.1.0"
description = "This is my prjoect bro"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=3.0.0",
    "pytest>=7.0.0",
]
