# .github/workflows/check-version-bump.yaml
name: Check version bump

on:
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # fetch last commit for diff

      - name: Check if pyproject.toml changed
        run: |
          if git diff --name-only origin/main...HEAD | grep -q pyproject.toml; then
            echo "pyproject.toml was changed"
          else
            echo "You must bump the version in pyproject.toml when merging to main"
            exit 1
          fi
